apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: data-analyzer-hpa
  namespace: mdb
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: data-analyzer
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 90
